### ISSUE TITLE
pysamstats import error

### ISSUE THREAD

**Issue by podpearson** [malariagen/binder#10]
After creating an environment using binder as a submodule, I'm finding I can't import pysamstats:
```
$ python
Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 02:32:25) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysamstats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/team112_internal/rp7/src/github/malariagen/Pf-6.0-public-release/deps/conda/envs/Pf-6.0-public-release/lib/python3.6/site-packages/pysamstats/__init__.py", line 8, in <module>
    from .pileup import *
  File "/nfs/team112_internal/rp7/src/github/malariagen/Pf-6.0-public-release/deps/conda/envs/Pf-6.0-public-release/lib/python3.6/site-packages/pysamstats/pileup.py", line 6, in <module>
    import pysamstats.opt as opt
  File "libcfaidx.pxd", line 52, in init pysamstats.opt
AttributeError: module 'pysam.libcfaidx' has no attribute 'FastxRecord'
```
@alimanfoo any suggestions?

**Comment by alimanfoo** [comment]
Hi @podpearson, sorry for slow follow up on this one. Bottom line I don't know why this has happened, this error usually indicates an incompatibility between pysamstats and pysam versions but these **should** both be pinned to compatible versions in the environment, so something funky is going on. Can you do ``conda list`` to see what versions of pysamstats and pysam have been installed?
