### ISSUE TITLE
Errors running install-conda on Mac

### ISSUE THREAD

**Issue by leehart** [malariagen/binder#98]
```
[...]
Successfully built crcmod gcs-oauth2-boto-plugin google-apitools gsutil livereload pathtools petlx port-for prettypandas pyu2f retry-decorator socksipy-branch sphinx-autobuild sphinx-bootstrap-theme
Failed to build anhima watchdog
Installing collected packages: alabaster, anhima, argcomplete, argh, babel, boto, cached-property, crcmod, pyu2f, google-reauth, socksipy-branch, retry-decorator, gcs-oauth2-boto-plugin, google-apitools, pbr, mock, gsutil, imagesize, livereload, pathtools, petlx, port-for, prettypandas, pyerf, scikits-bootstrap, snowballstemmer, sphinxcontrib-devhelp, sphinxcontrib-htmlhelp, sphinxcontrib-applehelp, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-serializinghtml, sphinx, watchdog, sphinx-autobuild, sphinx-bootstrap-theme
    Running setup.py install for anhima: started
    Running setup.py install for anhima: finished with status 'error'

Pip subprocess error:
  ERROR: Command errored out with exit status 1:
   command: /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-install-deafcw9a/anhima/setup.py'"'"'; __file__='"'"'/private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-install-deafcw9a/anhima/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-wheel-zvtr8xp8
       cwd: /private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-install-deafcw9a/anhima/
  Complete output (45 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/sf.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/tree.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/sim.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/ld.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/compat.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/loc.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/af.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/util.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/mds.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/gt.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/io.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/pca.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/ped.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/h5.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/dist.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  copying ./anhima/f2.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
  creating build/lib.macosx-10.9-x86_64-3.7/anhima/opt
  copying ./anhima/opt/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/anhima/opt
  running build_ext
  building 'anhima.opt.ld' extension
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/anhima
  creating build/temp.macosx-10.9-x86_64-3.7/anhima/opt
  x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include -I/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib/python3.7/site-packages/numpy/core/include -I/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include/python3.7m -c anhima/opt/ld.c -o build/temp.macosx-10.9-x86_64-3.7/anhima/opt/ld.o
  clang-10: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
  In file included from anhima/opt/ld.c:629:
  In file included from /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
  In file included from /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:
  /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it with " \
   ^
  1 warning generated.
  x86_64-apple-darwin13.4.0-clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -L/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -L/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -L/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/anhima/opt/ld.o -o build/lib.macosx-10.9-x86_64-3.7/anhima/opt/ld.cpython-37m-darwin.so
  ld: warning: -pie being ignored. It is only used when linking a main executable
  ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
  clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for anhima
  ERROR: Command errored out with exit status 1:
   command: /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-install-deafcw9a/watchdog/setup.py'"'"'; __file__='"'"'/private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-install-deafcw9a/watchdog/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-wheel-unsra3gl
       cwd: /private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-install-deafcw9a/watchdog/
  Complete output (55 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/watchdog
  copying src/watchdog/watchmedo.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog
  copying src/watchdog/version.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog
  copying src/watchdog/events.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog
  copying src/watchdog/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog
  creating build/lib.macosx-10.9-x86_64-3.7/watchdog/utils
  copying src/watchdog/utils/unicode_paths.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/utils
  copying src/watchdog/utils/compat.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/utils
  copying src/watchdog/utils/win32stat.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/utils
  copying src/watchdog/utils/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/utils
  copying src/watchdog/utils/dirsnapshot.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/utils
  copying src/watchdog/utils/delayed_queue.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/utils
  copying src/watchdog/utils/platform.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/utils
  copying src/watchdog/utils/bricks.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/utils
  copying src/watchdog/utils/echo.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/utils
  creating build/lib.macosx-10.9-x86_64-3.7/watchdog/observers
  copying src/watchdog/observers/fsevents.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/observers
  copying src/watchdog/observers/inotify.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/observers
  copying src/watchdog/observers/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/observers
  copying src/watchdog/observers/api.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/observers
  copying src/watchdog/observers/inotify_buffer.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/observers
  copying src/watchdog/observers/winapi.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/observers
  copying src/watchdog/observers/read_directory_changes.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/observers
  copying src/watchdog/observers/kqueue.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/observers
  copying src/watchdog/observers/inotify_c.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/observers
  copying src/watchdog/observers/polling.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/observers
  copying src/watchdog/observers/fsevents2.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/observers
  creating build/lib.macosx-10.9-x86_64-3.7/watchdog/tricks
  copying src/watchdog/tricks/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/watchdog/tricks
  running egg_info
  writing src/watchdog.egg-info/PKG-INFO
  writing dependency_links to src/watchdog.egg-info/dependency_links.txt
  writing entry points to src/watchdog.egg-info/entry_points.txt
  writing requirements to src/watchdog.egg-info/requires.txt
  writing top-level names to src/watchdog.egg-info/top_level.txt
  reading manifest file 'src/watchdog.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.h' under directory 'src'
  writing manifest file 'src/watchdog.egg-info/SOURCES.txt'
  running build_ext
  building '_watchdog_fsevents' extension
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/src
  x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include -DWATCHDOG_VERSION_STRING="0.10.3" -DWATCHDOG_VERSION_MAJOR=0 -DWATCHDOG_VERSION_MINOR=10 -DWATCHDOG_VERSION_BUILD=3 -I/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include/python3.7m -c src/watchdog_fsevents.c -o build/temp.macosx-10.9-x86_64-3.7/src/watchdog_fsevents.o -std=c99 -pedantic -Wall -Wextra -fPIC -Wno-nullability-completeness -Wno-nullability-extension -Wno-newline-eof -Wno-error=unused-command-line-argument
  clang-10: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
  x86_64-apple-darwin13.4.0-clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -L/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -L/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -L/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/src/watchdog_fsevents.o -lm -o build/lib.macosx-10.9-x86_64-3.7/_watchdog_fsevents.cpython-37m-darwin.so -framework CoreFoundation -framework CoreServices
  ld: warning: -pie being ignored. It is only used when linking a main executable
  ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libm.tbd' for architecture x86_64
  clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for watchdog
DEPRECATION: Could not build wheels for anhima, watchdog which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
    ERROR: Command errored out with exit status 1:
     command: /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-install-deafcw9a/anhima/setup.py'"'"'; __file__='"'"'/private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-install-deafcw9a/anhima/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-record-_pyfs8tn/install-record.txt --single-version-externally-managed --compile --install-headers /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include/python3.7m/anhima
         cwd: /private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-install-deafcw9a/anhima/
    Complete output (45 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/sf.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/tree.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/sim.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/ld.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/compat.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/loc.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/af.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/util.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/mds.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/gt.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/io.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/pca.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/ped.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/h5.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/dist.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    copying ./anhima/f2.py -> build/lib.macosx-10.9-x86_64-3.7/anhima
    creating build/lib.macosx-10.9-x86_64-3.7/anhima/opt
    copying ./anhima/opt/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/anhima/opt
    running build_ext
    building 'anhima.opt.ld' extension
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/anhima
    creating build/temp.macosx-10.9-x86_64-3.7/anhima/opt
    x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include -I/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib/python3.7/site-packages/numpy/core/include -I/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include/python3.7m -c anhima/opt/ld.c -o build/temp.macosx-10.9-x86_64-3.7/anhima/opt/ld.o
    clang-10: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
    In file included from anhima/opt/ld.c:629:
    In file included from /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
    In file included from /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:
    /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it with " \
     ^
    1 warning generated.
    x86_64-apple-darwin13.4.0-clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -L/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -L/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -L/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/anhima/opt/ld.o -o build/lib.macosx-10.9-x86_64-3.7/anhima/opt/ld.cpython-37m-darwin.so
    ld: warning: -pie being ignored. It is only used when linking a main executable
    ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
    clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-install-deafcw9a/anhima/setup.py'"'"'; __file__='"'"'/private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-install-deafcw9a/anhima/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/pip-record-_pyfs8tn/install-record.txt --single-version-externally-managed --compile --install-headers /Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/envs/vector-ops-v2.5.1/include/python3.7m/anhima Check the logs for full command output.

Traceback (most recent call last):
  File "/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 111, in execute
    result[installer_type] = installer.install(prefix, pkg_specs, args, env)
  File "/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/lib/python3.8/site-packages/conda_env/installers/pip.py", line 46, in _pip_install_via_requirements
    stdout, stderr = pip_subprocess(pip_cmd, prefix, cwd=pip_workdir)
  File "/Users/lee/Desktop/work/gitRepos/vector-ops/binder/deps/conda/lib/python3.8/site-packages/conda_env/pip_util.py", line 41, in pip_subprocess
    raise CondaEnvException("Pip failed")
conda_env.exceptions.CondaEnvException: Pip failed
```

**Comment by leehart** [comment]
See comments in #1470
